name: "Hello Actions"
decription: "Greet someone"
author: "octocat@github.com"

inputs:
    MY_NAME:
        decription: "Who to greet"
        required: true
        default: "World"
        
runs:
    using: "docker"
    image: "Dockerfile"
    
branding:
    icon: "mic"
    color: "purple"